# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^grammars/.*$
    -   id: end-of-file-fixer
        exclude: ^grammars/.*$
    -   id: check-yaml
        exclude: ^grammars/.*$
    -   id: check-added-large-files
        exclude: ^grammars/.*$
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: bash -c 'find srcs tests -type f \( -iname "*.cc" -o -iname "*.h" -o -iname "*.hpp" -o -iname "*.cpp" \) -exec clang-format -style=file -i {} +'
        language: system
        stages: [commit]
