name: Build

on:
  push:

jobs:
  linux:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-22.04]
    env:
      AFL_SKIP_CPUFREQ: 1
      AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: sudo apt-get install -y build-essential clang llvm-dev libc++-dev python3-dev python3-setuptools cmake git
      - name: pull submodule
        run: git submodule update --init
      - name: build
        run: make && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug && make -j