name: Build

on:
  push:

jobs:
  linux:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-22.04]
    env:
      AFL_SKIP_CPUFREQ: 1
      AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
      CC: gcc
      CXX: g++
      POLYGLOT_ROOT: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: sudo apt-get install -y build-essential clang llvm-dev libc++-dev python3-dev python3-setuptools cmake git python3-pip lcov
      - name: pull submodule
        run: git submodule update --init
      - name: build afl
        run: cd AFLplusplus && make -j && sudo ./afl-system-config
      - name: install conan
        run: pip3 install conan fire
      - name: install conan profile
        run: conan profile detect
      - name: build
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DGRAMMAR_FILE=$POLYGLOT_ROOT/experiments/SimpleLang.g4 -DCODE_COVERAGE=ON && make -j
      - name: unittest
        run: cd build && ctest
      - name: Generate Coverage Report
        run: cd build && lcov --directory . --capture --output-file coverage.info && lcov --remove coverage.info '/usr/*' --output-file coverage.info && lcov --remove coverage.info '/*/experiments/generated/*' --output-file coverage.info && lcov --remove coverage.info  '/*/.conan2/*' --output-file coverage.info && lcov --list coverage.info
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: build/coverage.info
      - name: end to end test
        run: cd e2e_tests && bash ./run.sh
